#!/bin/bash


ping=(`ping -c 1 -t 1 8.8.8.8 | grep "100.0% packet loss"`)

if [[ -n $ping ]]
then
	echo "[ NaN ]"
	exit
fi

password=$(security 2>&1 >/dev/null find-generic-password -s gmail -g |ruby -e 'print $1 if STDIN.gets =~ /^password: "(.*)"$/')
count=$(curl -u my@email.email:$password --silent "https://mail.google.com/mail/feed/atom" | awk -F "fullcount" '{ print $2 }' | sed 's/[></]//g')
 
if [[ $count -gt 0 ]]
then
	if [[ $count -gt 1 ]]
	then
		if [[ $count -gt 5 ]]
		then
			output="#[fg=red]$count Personal emails"
		else
			output="$count Personal emails"
		fi
	else
		output="$count Personal email"
	fi

	echo "[ "$output"#[default] ]"
else
	echo "[-]"
fi
